import type { FontOption } from "../types";

export const DEFAULT_FONT_LABEL = "Cormorant Garamond";
export const DEFAULT_FONT_CSS = "Cormorant Garamond, Garamond, serif";

export const FONT_OPTIONS: FontOption[] = [
	{
		label: "Cormorant Garamond",
		css: "Cormorant Garamond, Garamond, serif",
		google: "Cormorant Garamond",
	},
	{ label: "Cormorant", css: "Cormorant, Garamond, serif", google: "Cormorant" },
	{
		label: "Cormorant Infant",
		css: "Cormorant Infant, Garamond, serif",
		google: "Cormorant Infant",
	},
	{ label: "Cormorant SC", css: "Cormorant SC, Garamond, serif", google: "Cormorant SC" },
	{
		label: "Cormorant Unicase",
		css: "Cormorant Unicase, Garamond, serif",
		google: "Cormorant Unicase",
	},
	{ label: "EB Garamond", css: "EB Garamond, Garamond, serif", google: "EB Garamond" },
	{ label: "Crimson Pro", css: "Crimson Pro, Garamond, serif", google: "Crimson Pro" },
	{ label: "Alegreya", css: "Alegreya, Georgia, serif", google: "Alegreya" },
	{ label: "Source Serif 4", css: "Source Serif 4, Georgia, serif", google: "Source Serif 4" },
	{ label: "Lora", css: "Lora, Georgia, serif", google: "Lora" },
	{ label: "Alegreya SC", css: "Alegreya SC, Georgia, serif", google: "Alegreya SC" },
	{ label: "Arvo", css: "Arvo, Georgia, serif", google: "Arvo" },
	{ label: "Bitter", css: "Bitter, Georgia, serif", google: "Bitter" },
	{ label: "Bodoni Moda", css: "Bodoni Moda, Didot, serif", google: "Bodoni Moda" },
	{ label: "Bree Serif", css: "Bree Serif, Georgia, serif", google: "Bree Serif" },
	{ label: "Cardo", css: "Cardo, Georgia, serif", google: "Cardo" },
	{ label: "Cinzel", css: "Cinzel, Georgia, serif", google: "Cinzel" },
	{ label: "Copse", css: "Copse, Georgia, serif", google: "Copse" },
	{
		label: "Cormorant Upright",
		css: "Cormorant Upright, Garamond, serif",
		google: "Cormorant Upright",
	},
	{ label: "Crimson Text", css: "Crimson Text, Georgia, serif", google: "Crimson Text" },
	{
		label: "DM Serif Display",
		css: "DM Serif Display, Georgia, serif",
		google: "DM Serif Display",
	},
	{ label: "DM Serif Text", css: "DM Serif Text, Georgia, serif", google: "DM Serif Text" },
	{ label: "Domine", css: "Domine, Georgia, serif", google: "Domine" },
	{ label: "Fauna One", css: "Fauna One, Georgia, serif", google: "Fauna One" },
	{ label: "Forum", css: "Forum, Georgia, serif", google: "Forum" },
	{ label: "Gloock", css: "Gloock, Georgia, serif", google: "Gloock" },
	{ label: "Inknut Antiqua", css: "Inknut Antiqua, Georgia, serif", google: "Inknut Antiqua" },
	{ label: "Joan", css: "Joan, Georgia, serif", google: "Joan" },
	{
		label: "Libre Baskerville",
		css: "Libre Baskerville, Baskerville, serif",
		google: "Libre Baskerville",
	},
	{
		label: "Libre Caslon Display",
		css: "Libre Caslon Display, Baskerville, serif",
		google: "Libre Caslon Display",
	},
	{ label: "Literata", css: "Literata, Georgia, serif", google: "Literata" },
	{ label: "Maitree", css: "Maitree, Georgia, serif", google: "Maitree" },
	{ label: "Merriweather", css: "Merriweather, Georgia, serif", google: "Merriweather" },
	{ label: "Neuton", css: "Neuton, Georgia, serif", google: "Neuton" },
	{ label: "Newsreader", css: "Newsreader, Georgia, serif", google: "Newsreader" },
	{ label: "Noto Serif", css: "Noto Serif, Georgia, serif", google: "Noto Serif" },
	{ label: "Old Standard TT", css: "Old Standard TT, Georgia, serif", google: "Old Standard TT" },
	{ label: "Oranienbaum", css: "Oranienbaum, Georgia, serif", google: "Oranienbaum" },
	{ label: "Petrona", css: "Petrona, Georgia, serif", google: "Petrona" },
	{
		label: "Playfair Display",
		css: "Playfair Display, Georgia, serif",
		google: "Playfair Display",
	},
	{
		label: "Playfair Display SC",
		css: "Playfair Display SC, Georgia, serif",
		google: "Playfair Display SC",
	},
	{ label: "Prata", css: "Prata, Georgia, serif", google: "Prata" },
	{ label: "PT Serif", css: "PT Serif, Georgia, serif", google: "PT Serif" },
	{ label: "Quattrocento", css: "Quattrocento, Georgia, serif", google: "Quattrocento" },
	{ label: "Radley", css: "Radley, Georgia, serif", google: "Radley" },
	{ label: "Rokkitt", css: "Rokkitt, Georgia, serif", google: "Rokkitt" },
	{ label: "Rosarivo", css: "Rosarivo, Georgia, serif", google: "Rosarivo" },
	{ label: "Rufina", css: "Rufina, Georgia, serif", google: "Rufina" },
	{ label: "Slabo 27px", css: "Slabo 27px, Georgia, serif", google: "Slabo 27px" },
	{
		label: "Sorts Mill Goudy",
		css: "Sorts Mill Goudy, Georgia, serif",
		google: "Sorts Mill Goudy",
	},
	{ label: "Spectral", css: "Spectral, Georgia, serif", google: "Spectral" },
	{ label: "Tinos", css: "Tinos, Georgia, serif", google: "Tinos" },
	{ label: "Trirong", css: "Trirong, Georgia, serif", google: "Trirong" },
	{ label: "Vollkorn", css: "Vollkorn, Georgia, serif", google: "Vollkorn" },
	{ label: "Vidaloka", css: "Vidaloka, Georgia, serif", google: "Vidaloka" },
	{ label: "Yrsa", css: "Yrsa, Georgia, serif", google: "Yrsa" },
	{ label: "Zilla Slab", css: "Zilla Slab, Georgia, serif", google: "Zilla Slab" },
	{ label: "Baskervville", css: "Baskervville, Baskerville, serif", google: "Baskervville" },
	{ label: "Alice", css: "Alice, Georgia, serif", google: "Alice" },
	{ label: "Lusitana", css: "Lusitana, Georgia, serif", google: "Lusitana" },
];
